# Generated automatically from Makefile.in by configure.
 
.PHONY:	default all install depend clean targetclean

subdirs = libipv1 libciomr libparse alloc io iomr iomrth \
          libcoallc libmalloc libfile30


all: default

default:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making in $${dir} ...; $(MAKE) default); \
          done

install:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making install in $${dir} ...; $(MAKE) install); \
          done

install_inc:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making install in $${dir} ...; $(MAKE) install_inc); \
          done

install_man:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making install in $${dir} ...; $(MAKE) install_man); \
          done

depend:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making depend in $${dir} ...; $(MAKE) depend); \
          done

clean:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making clean in $${dir} ...; $(MAKE) clean); \
          done

targetclean:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making clean in $${dir} ...; $(MAKE) targetclean); \
          done


#
# keep the configuration information and makefile up-to-date
#

top_srcdir = /home/usrb/b3/longhorn/psi
srcdir = /home/usrb/b3/longhorn/psi/src/lib
top_objdir = /home/usrb/b3/longhorn/psi

