# Generated automatically from Makefile.in by configure.

.PHONY:	default all install depend clean targetclean

subdirs = tmpl psipp

all: default

default:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making in $${dir} ...; $(MAKE) default); \
          done

install:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making install in $${dir} ...; $(MAKE) install); \
          done

install_inc:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making install in $${dir} ...; $(MAKE) install_inc); \
          done

install_man:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making install in $${dir} ...; $(MAKE) install_man); \
          done

depend:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making depend in $${dir} ...; $(MAKE) depend); \
          done

clean:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making clean in $${dir} ...; $(MAKE) clean); \
          done

targetclean:
	for dir in $(subdirs); \
          do \
            (cd $${dir}; echo ... Making clean in $${dir} ...; $(MAKE) targetclean); \
          done

top_srcdir = /home/usrb/b3/longhorn/psi
srcdir = /home/usrb/b3/longhorn/psi/src/util
top_objdir = /home/usrb/b3/longhorn/psi

